version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=testcluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
    volumes:
      - namenode-data:/hadoop/dfs/name
    ports:
      - 9000:9000 # Namenode RPC
      - 9870:9870 # Namenode Web UI
    networks:
      - hadoopnet

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - CLUSTER_NAME=testcluster
      - SERVICE_PRECONDITION=namenode:9000
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode
    ports:
      - 9864:9864 # Datanode Web UI
    networks:
      - hadoopnet

  spark:
    image: bitnami/spark:3.5.0
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_CONF_DIR=/opt/bitnami/hadoop/etc/hadoop
    volumes:
      - ./hadoop-conf:/opt/bitnami/hadoop/etc/hadoop # 自定义配置放这里，可选
    depends_on:
      - namenode
      - datanode
    ports:
      - 7077:7077 # Spark Master
      - 8080:8080 # Spark UI
      - 4040:4040 # Spark Application UI
    networks:
      - hadoopnet

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_CONF_DIR=/opt/bitnami/hadoop/etc/hadoop
    depends_on:
      - spark
    networks:
      - hadoopnet

volumes:
  namenode-data:
  datanode-data:


networks:
  hadoopnet:
    driver: bridge
